version: beta

serial:
  baudrate: 1000000

motors:
  - body_yaw:
      id: 10
      offset: 0
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_1:
      id: 11
      offset: 1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_2:
      id: 12
      offset: -1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_3:
      id: 13
      offset: 1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_4:
      id: 14
      offset: -1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_5:
      id: 15
      offset: 1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - stewart_platform_6:
      id: 16
      offset: -1024
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - right_antenna:
      id: 17
      offset: 0
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52
  - left_antenna:
      id: 18
      offset: 0
      lower_limit: 0
      upper_limit: 4095
      return_delay_time: 0
      shutdown_error: 52