#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SERVICE_NAME="gpio-shutdown-daemon"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
LAUNCHER_PATH="$SCRIPT_DIR/launcher.sh"

# Install the packaged static unit file (single source of truth). Its
# ExecStart expects the SDK installed at /venvs/mini_daemon — the fleet
# layout. The wireless startup check (startup_check.py) re-syncs this unit
# on every boot, so a unit generated by an older SDK heals itself.
sudo cp "$SCRIPT_DIR/${SERVICE_NAME}.service" "$SERVICE_FILE"

chmod +x "$LAUNCHER_PATH"

# Reload systemd, enable and start the service
sudo systemctl daemon-reload
sudo systemctl enable --now $SERVICE_NAME

echo "Service '$SERVICE_NAME' installed and started."
