// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT.
// Source of truth is the `version` field in package.json (bumped by CI at
// release). Regenerated by the `prebuild:sdk` npm lifecycle hook.
export const SDK_VERSION = "0.0.0-managed-by-ci";
