// Generates lib/version.ts from package.json so the SDK can report its
// own build version at runtime.
//
// Why generate instead of hardcoding: package.json is the single source
// of truth npm publishes, and CI bumps it at release time (see RELEASE).
// A hand-written constant would drift; deriving it here keeps the runtime
// value byte-identical with what ends up on npm — zero maintenance.
//
// Runs automatically via the `prebuild:sdk` npm lifecycle hook. The output
// (lib/version.ts) is committed with the placeholder value so typecheck /
// editors work without a build; CI regenerates it after the version bump.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;

const out = `// AUTO-GENERATED by scripts/gen-version.mjs — DO NOT EDIT.
// Source of truth is the \`version\` field in package.json (bumped by CI at
// release). Regenerated by the \`prebuild:sdk\` npm lifecycle hook.
export const SDK_VERSION = ${JSON.stringify(version)};
`;

const target = join(root, "lib", "version.ts");
writeFileSync(target, out);
console.log(`[gen-version] wrote ${target} (SDK_VERSION=${version})`);
